<a href="https://colab.research.google.com/github/EmileNapon/Angular/blob/main/Cr%C3%A9ation_avanc%C3%A9e_de_tableaux_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercice 1

Crée un tableau contenant tous les entiers de 5 à 25 inclus, avec un pas de 2

In [ ]:
import numpy as np

In [ ]:
np.arange(5,26,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

Exercice 2

Crée un tableau de 50 valeurs entre 0 et 1 inclus, espacées régulièrement.

In [ ]:
np.linspace(0,1, 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

Exercice 3

Crée une matrice 4×4 remplie uniquement de la valeur 9.

In [ ]:
np.full((4,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

Exercice 4

Crée une matrice identité 6×6, puis remplace la diagonale par [1, 2, 3, 4, 5, 6].

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.diag([1, 2, 3, 4, 5, 6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

Exercice 5


À partir du tableau :
base = np.array([0, 1, 2])
Crée un tableau qui répète chaque élément 4 fois.


In [ ]:
base = np.array([0, 1, 2])

In [ ]:
base

array([0, 1, 2])

In [ ]:
np.repeat(base, 4)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

Exercice 6

Crée un tableau 5×5 contenant les coordonnées i+j pour chaque position (utilise
fromfunction).

In [ ]:
def f(i,j):
    return i+j
np.fromfunction(f,(5,5))

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.],
       [3., 4., 5., 6., 7.],
       [4., 5., 6., 7., 8.]])

Exercice 7


Crée une grille 2D (meshgrid) de x et y dans l’intervalle [-2, 2] avec 9 points, puis crée un
tableau Z = X² + Y².

In [ ]:
x=np.linspace(-2,2,9)
y=np.linspace(-2,2,9)

X, Y = np.meshgrid(x, y)
Z = X**2 + Y**2

In [ ]:
x,y

(array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ]),
 array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ]))

In [ ]:
Z

array([[8.  , 6.25, 5.  , 4.25, 4.  , 4.25, 5.  , 6.25, 8.  ],
       [6.25, 4.5 , 3.25, 2.5 , 2.25, 2.5 , 3.25, 4.5 , 6.25],
       [5.  , 3.25, 2.  , 1.25, 1.  , 1.25, 2.  , 3.25, 5.  ],
       [4.25, 2.5 , 1.25, 0.5 , 0.25, 0.5 , 1.25, 2.5 , 4.25],
       [4.  , 2.25, 1.  , 0.25, 0.  , 0.25, 1.  , 2.25, 4.  ],
       [4.25, 2.5 , 1.25, 0.5 , 0.25, 0.5 , 1.25, 2.5 , 4.25],
       [5.  , 3.25, 2.  , 1.25, 1.  , 1.25, 2.  , 3.25, 5.  ],
       [6.25, 4.5 , 3.25, 2.5 , 2.25, 2.5 , 3.25, 4.5 , 6.25],
       [8.  , 6.25, 5.  , 4.25, 4.  , 4.25, 5.  , 6.25, 8.  ]])